version: '3.8'

services:
  # PostgreSQL база данных для всех микросервисов LAVANDA
  postgres:
    image: postgres:15-alpine
    container_name: lavanda-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lavanda
      POSTGRES_USER: lavanda_user
      POSTGRES_PASSWORD: lavanda_password
      POSTGRES_MULTIPLE_DATABASES: lavanda_orders,lavanda_inventory,lavanda_finance
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - lavanda-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lavanda_user -d lavanda"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis для кэширования и сессий
  redis:
    image: redis:7-alpine
    container_name: lavanda-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lavanda-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # pgAdmin для управления базой данных (опционально)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lavanda-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lavanda.ru
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - lavanda-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  lavanda-network:
    driver: bridge
    name: lavanda-network
